development:
  adapter: postgis
  encoding: unicode
  database: bus_detective_development

test:
  adapter: postgis
  encoding: unicode
  database: bus_detective_test

production:
  adapter: postgis
  encoding: unicode
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

